name: Generate ASCII Artwork

on: push

jobs: 
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Execute Shell Script
          run: bash ascii-generate.sh

    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Sleep 10
          run: sleep 10
        
        - name: Test File Exists
          run: grep -i "dragon" dragon.txt
                
    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
        
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying...
            
            

